#
# pixi.toml Project Config
#

# Project --------------------------------------------------------------------------------------------------------------
[project]
channels = ["conda-forge", ]
platforms = ["linux-64"]
name = "Py-C108"
authors = ["Carbon108"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/C108-Lab/c108"

# Feature: Default -----------------------------------------------------------------------------------------------------
[dependencies]
python = ">=3.10"
pip = "*"

# Feature: test --------------------------------------------------------------------------------------------------------
[feature.test.dependencies]
pytest = ">=8.0"
pytest-cov = ">=5.0"

# Feature: dev ---------------------------------------------------------------------------------------------------------
[feature.dev.dependencies]
astropy = "*"
jax = "*"
numpy = "*"
pandas = "*"
pytest-rerunfailures = "*"
pytorch = "*"
ruff = "*"
sympy = "*"
tensorflow = "*"
xdoctest = "*"

# ENV-s ----------------------------------------------------------------------------------------------------------------
[environments]
dev = ["dev", "test"]

# SHELL ----------------------------------------------------------------------------------------------------------------
[activation]
env = { PYTHONPATH = "$PYTHONPATH:$PIXI_PROJECT_ROOT" }
